language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - add-on
    - extra
licenses:
    - 'android-sdk-license-.+'
before_install:
    - yes | sdkmanager "platforms;android-27"
jdk:
    - oraclejdk8
before_script:
    - chmod +x gradlew
script:
    - ./gradlew assembleDebug
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  provider: releases
  api_key:
    secure: 20e8c50c2561bb17bb631481cb63252f7490c0d1
  file: app/build/outputs/apk/buff.apk
  skip_cleanup: true
